version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
        - certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - html:/usr/share/nginx/html:rw


  whoami1:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami1.hbjnmcd.ru
      - LETSENCRYPT_HOST=whoami1.hbjnmcd.ru
      - LETSENCRYPT_EMAIL=the.nat.cool@gmail.com
  whoami2:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami2.hbjnmcd.ru
      - LETSENCRYPT_HOST=whoami2.hbjnmcd.ru
      - LETSENCRYPT_EMAIL=the.nat.cool@gmail.com

volumes:
  conf:
  vhost:
  html:
  certs:
  dhparam:
